name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dirs
        run: |
          mkdir -p toolchain iOS_SDK

      - name: Download iOS toolchain (multiple mirrors + retry)
        shell: bash
        run: |
          set -e
          urls=(
            "https://github.com/theos/toolchain-linux/releases/download/13.0/toolchain-linux-ios-13.0.tar.xz"
            "https://download.fastgit.org/theos/toolchain-linux/releases/download/13.0/toolchain-linux-ios-13.0.tar.xz"
          )
          for u in "${urls[@]}"; do
            echo "Trying $u"
            if curl -L --retry 5 --retry-delay 2 -o toolchain.tar.xz "$u"; then
              echo "OK: $u"; break
            fi
          done
          tar -xJf toolchain.tar.xz -C toolchain --strip-components=1
          ls -lah toolchain/usr/bin | head

      - name: Download iPhoneOS 14.5 SDK (multiple mirrors + retry)
        shell: bash
        run: |
          set -e
          urls=(
            "https://github.com/qnblackcat/awesome-iOS/releases/download/ios-sdks/iPhoneOS14.5.sdk.tar.xz"
            "https://download.fastgit.org/qnblackcat/awesome-iOS/releases/download/ios-sdks/iPhoneOS14.5.sdk.tar.xz"
          )
          for u in "${urls[@]}"; do
            echo "Trying $u"
            if curl -L --retry 5 --retry-delay 2 -o iOS_SDK/iPhoneOS14.5.sdk.tar.xz "$u"; then
              echo "OK: $u"; break
            fi
          done
          tar -xJf iOS_SDK/iPhoneOS14.5.sdk.tar.xz -C iOS_SDK
          ls -lah iOS_SDK

      - name: Build dylib
        env:
            TOOLCHAIN_ROOT: ${{ github.workspace }}/toolchain/usr
            SDK_PATH: ${{ github.workspace }}/iOS_SDK
            SDK: iPhoneOS14.5.sdk
            ARCH: arm64
            MIN_IOS: "12.0"
        run: |
          export PATH="$TOOLCHAIN_ROOT/bin:$PATH"
          make TOOLCHAIN_ROOT="$TOOLCHAIN_ROOT" SDK_PATH="$SDK_PATH" SDK="$SDK" ARCH="$ARCH" MIN_IOS="$MIN_IOS"
          file KnPatch.dylib
          ls -lh KnPatch.dylib

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KnPatch-dylib
          path: KnPatch.dylib
          retention-days: 7
