name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 安装 theos + sdks + toolchain
      - name: Install theos, toolchain and SDKs
        shell: bash
        run: |
          set -euo pipefail

          echo "Clang on runner:"
          clang --version

          # 拉 theos
          if [ ! -d "$THEOS" ]; then
            git clone --depth=1 https://github.com/theos/theos.git "$THEOS"
          fi

          # 拉 sdks
          if [ ! -d "$THEOS/sdks" ]; then
            git clone --depth=1 https://github.com/theos/sdks.git "$THEOS/sdks"
          fi

          # 拉 iOS toolchain for linux
          if [ ! -d "$THEOS/toolchain" ]; then
            mkdir -p "$THEOS/toolchain"
            curl -L https://github.com/theos/toolchain-linux/releases/download/13.0/toolchain-linux-ios-13.0.tar.xz -o toolchain.tar.xz
            tar -xJf toolchain.tar.xz -C "$THEOS/toolchain"
          fi

          echo "Available SDKs:"
          ls -1 "$THEOS/sdks" || true
          echo "Available toolchains:"
          ls -R "$THEOS/toolchain" || true

      - name: Force TARGET to iOS 14.4
        shell: bash
        run: |
          if [ -f Makefile ]; then
            if grep -qE '^[[:space:]]*TARGET[[:space:]]*:=' Makefile; then
              sed -i 's/^[[:space:]]*TARGET[[:space:]]*.*/TARGET := iphone:clang:latest:14.4/' Makefile
            else
              printf "\nTARGET := iphone:clang:latest:14.4\n" >> Makefile
            fi
            echo "Makefile TARGET set to iphone:clang:latest:14.4"
          fi

      - name: Build dylib
        shell: bash
        run: |
          make clean || true
          make
          echo "Build done. Listing outputs:"
          ls -al

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KnPatch-iOS14.4
          path: |
            ./*.dylib
            ./*.plist
            ./build/**/*.dylib
            ./build/**/*.plist
          if-no-files-found: warn
