name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      THEOS: ${{ github.workspace }}/theos   # /home/runner/work/<repo>/<repo>/theos
      SDK_VER: 14.5                          # 用 14.5 的 SDK，能在 14.4 跑
      MIN_VER: 12.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install theos, toolchain and SDKs
        shell: bash
        run: |
          set -eux
          mkdir -p "$THEOS"

          echo "::group::Download toolchain"
          # 每次都先删，避免空目录/坏缓存导致找不到 clang
          rm -rf "$THEOS/toolchain"
          curl -L -o toolchain.tar.xz \
            https://github.com/theos/toolchain-linux/releases/latest/download/toolchain-linux-ios.tar.xz
          tar -xJf toolchain.tar.xz -C "$THEOS"
          ls -l "$THEOS/toolchain/usr/bin/clang"
          echo "::endgroup::"

          echo "::group::Download iPhoneOS SDK"
          mkdir -p "$THEOS/sdks"
          rm -rf "$THEOS/sdks/iPhoneOS${SDK_VER}.sdk"
          curl -L -o sdk.tar.xz \
            https://github.com/theos/sdks/releases/download/${SDK_VER}/iPhoneOS${SDK_VER}.sdk.tar.xz
          tar -xJf sdk.tar.xz -C "$THEOS/sdks"
          ls -d "$THEOS/sdks/iPhoneOS${SDK_VER}.sdk"
          echo "::endgroup::"

      - name: Force TARGET to iOS 14.4 (optional safety)
        shell: bash
        run: |
          sed -i 's/^TARGET.*/TARGET := iphone:clang:latest:14.4/' Makefile || true

      - name: Build dylib
        shell: bash
        run: |
          set -eux
          make clean || true
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KnPatch.dylib
          path: KnPatch.dylib
