name: build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ✅ 不再下载 .tar.xz；直接克隆 theos 和 sdks
      - name: Install iOS toolchain (theos + sdks)
        run: |
          sudo apt-get update
          sudo apt-get install -y git clang make curl xz-utils
          git clone --depth=1 https://github.com/theos/theos.git $GITHUB_WORKSPACE/theos
          git clone --depth=1 https://github.com/theos/sdks.git  $GITHUB_WORKSPACE/theos/sdks

      - name: Build dylib
        env:
          THEOS: ${{ github.workspace }}/theos
        run: |
          make clean
          make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: KnPatch-artifacts
          path: |
            ./*.dylib
            ./*.plist
            ./build/**/*.dylib
            ./build/**/*.plist
